server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
hu:
  webuni:
    secret:
      dir: .secret-keypair
      pub:
        key: jwt_rsa.pub
      secret:
        key: jwt_rsa.key
